<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./assets/tower/Models/GLB/detail-rocks-large.glb
-->

<script lang="ts">
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import { type Group, type Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	const gltf = useGltf('/assets/tower/Models/GLB/detail-rocks-large.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh scale={[1, 0.25, 1]} geometry={gltf.nodes['detail-rocks-large_1'].geometry}>
			<T.MeshBasicMaterial color="#2b2b2b" />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
