<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/custom/tacoShell.glb
-->

<script lang="ts">
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import { type Group, type Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	const gltf = useGltf('/assets/custom/tacoShell.glb');
</script>

<T.Group bind:ref dispose={false} {...props} scale={0.3}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Circle.geometry}
			material={gltf.nodes.Circle.material}
			position={[0.13, 0.1, 0.05]}
		>
			<T.MeshBasicMaterial color="#f5b042" />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
