<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/food/Models/GLB/tomato.glb
-->

<script lang="ts">
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import type { Group, Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	const gltf = useGltf('/assets/food/Models/GLB/tomato.glb');
</script>

<T.Group bind:ref dispose={false} {...props} scale={2}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.tomato_1.geometry} material={gltf.materials.colormap} />
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
