<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/arcade/Models/GLB/character-employee.glb
-->

<script lang="ts">
	import { playerData } from '$lib/sharedState.svelte';
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import { Group, type Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	ref = new Group();

	const gltf = useGltf('/assets/arcade/Models/GLB/character-employee.glb');

	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	let currentActionKey = 'idle';

	$effect(() => {
		// This effect acts like an init default pose
		$actions?.['idle']?.play();
	});

	$effect(() => {
		transitionTo(playerData.animationState, 0.3);
	});

	function transitionTo(actionKey: string, duration = 1) {
		const currentAction = $actions[currentActionKey];
		const nextAction = $actions[actionKey];
		if (!nextAction || currentAction === nextAction) return;
		// Function inspired by: https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
		nextAction.enabled = true;
		if (currentAction) {
			currentAction.crossFadeTo(nextAction, duration, true);
		}
		// Not sure why I need this but the source code does not
		nextAction.play();
		currentActionKey = actionKey;
	}
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="character-employee">
			<T.Group name="character-employee_1">
				<T is={gltf.nodes.root} />
				<T.SkinnedMesh
					name="body-mesh"
					geometry={gltf.nodes['body-mesh'].geometry}
					material={gltf.materials.colormap}
					skeleton={gltf.nodes['body-mesh'].skeleton}
				/>
				<T.SkinnedMesh
					name="head-mesh"
					geometry={gltf.nodes['head-mesh'].geometry}
					material={gltf.materials.colormap}
					skeleton={gltf.nodes['head-mesh'].skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
