<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/arcade/Models/GLB/character-employee.glb
-->

<script lang="ts">
	import { playerSpeed, realPlayerSpeed } from '$lib/sharedState.svelte';
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import { Group, type Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	ref = new Group();

	const gltf = useGltf('/assets/arcade/Models/GLB/character-employee.glb');

	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	$effect(() => {
		if (Math.abs(realPlayerSpeed.x) + Math.abs(realPlayerSpeed.x) > 0.1) {
			$actions?.['walk']?.play();
		} else {
			$actions?.['walk']?.stop();
			$actions?.['idle']?.play();
		}
	});
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="character-employee">
			<T.Group name="character-employee_1">
				<T is={gltf.nodes.root} />
				<T.SkinnedMesh
					name="body-mesh"
					geometry={gltf.nodes['body-mesh'].geometry}
					material={gltf.materials.colormap}
					skeleton={gltf.nodes['body-mesh'].skeleton}
				/>
				<T.SkinnedMesh
					name="head-mesh"
					geometry={gltf.nodes['head-mesh'].geometry}
					material={gltf.materials.colormap}
					skeleton={gltf.nodes['head-mesh'].skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
