<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/furniture/Models/GLTF/kitchenStove.glb
-->

<script lang="ts">
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';
	import type { Group, Object3DEventMap } from 'three';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
	} = $props();

	const gltf = useGltf('/assets/furniture/Models/GLTF/kitchenStove.glb');
</script>

<T.Group scale={2} bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Mesh_kitchenStove.geometry} material={gltf.materials.metal} />
		<T.Mesh geometry={gltf.nodes.Mesh_kitchenStove_1.geometry} material={gltf.materials.wood} />
		<T.Mesh
			geometry={gltf.nodes.Mesh_kitchenStove_2.geometry}
			material={gltf.materials.metalDark}
		/>
		<T.Mesh
			geometry={gltf.nodes.Mesh_kitchenStove_3.geometry}
			material={gltf.materials.carpetWhite}
		/>
		<T.Group position={[0.03, 0.09, -0.03]}>
			<T.Mesh geometry={gltf.nodes.Mesh_door.geometry} material={gltf.materials.metal} />
			<T.Mesh geometry={gltf.nodes.Mesh_door_1.geometry} material={gltf.materials.glass} />
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
