<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/assets/market/Models/GLB/display-fruit.glb
-->

<script lang="ts">
	/* eslint svelte/require-store-reactive-access: "off" */
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { Collider } from '@threlte/rapier';
	import type { Snippet } from 'svelte';
	import type { Group, Object3DEventMap } from 'three';
	import { playerData } from '../../routes/play/sharedState.svelte';
	import { registerEListener, unregisterEListener } from '../../routes/play/keyManager';
	import type { RigidBodyUserData } from '$lib/types/RigidBodyUserData';
	type Ref = Group<Object3DEventMap> | undefined;
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		id,
		...props
	}: {
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		children?: Snippet<[{ ref: Ref }]>;
		ref?: Ref;
		id: string;
	} = $props();

	const gltf = useGltf('/assets/market/Models/GLB/display-fruit.glb');

	let lastEvent: DOMHighResTimeStamp = 0;
	const pickup = () => {
		const n = performance.now();
		if (n - lastEvent < 300) {
			return;
		}
		lastEvent = performance.now();
		playerData.carrying = 'tomato';
	};
</script>

<Collider
	shape="cuboid"
	args={[0.5, 0.5, 0.5]}
	oncollisionenter={(e) => {
		if ((e.targetRigidBody?.userData as RigidBodyUserData).name == 'player') {
			registerEListener(id, pickup);
		}
	}}
	oncollisionexit={(e) => {
		if ((e.targetRigidBody?.userData as RigidBodyUserData).name == 'player') {
			unregisterEListener(id);
		}
	}}
>
	<T.Group bind:ref dispose={false} {...props} position={[0, -0.5, 0]} scale={[1.7, 2, 1.7]}>
		{#await gltf}
			{@render fallback?.()}
		{:then gltf}
			<T.Mesh
				geometry={gltf.nodes['display-fruit_1'].geometry}
				material={gltf.materials.colormap}
			/>
		{:catch err}
			{@render error?.({ error: err })}
		{/await}

		{@render children?.({ ref })}
	</T.Group>
</Collider>
